export function renderAdminPage(): string {
  return `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Albion Composition Admin</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#0d0f12;color:#eef1f5}*{box-sizing:border-box}body{margin:0;background:#0d0f12}button,input,textarea,select{font:inherit}.shell{max-width:1440px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}.muted{color:#8f98a5}.card{background:#15181d;border:1px solid #272c35;border-radius:16px;padding:18px}.toolbar{display:flex;gap:10px;flex-wrap:wrap}.tabs button,.btn{border:1px solid #343a45;background:#20242b;color:#fff;padding:10px 14px;border-radius:10px;cursor:pointer}.btn.primary{background:#f0b90b;color:#111;border-color:#f0b90b;font-weight:700}.btn.danger{border-color:#7c3030;color:#ffb4b4}.grid{display:grid;grid-template-columns:minmax(360px,1.1fr) minmax(420px,1fr);gap:18px}.list{display:grid;gap:10px;max-height:70vh;overflow:auto}.row{padding:13px;border:1px solid #2b3039;border-radius:12px;background:#111419;cursor:pointer}.row:hover{border-color:#596170}.row-title{font-weight:700}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:6px}.field.full{grid-column:1/-1}label{font-size:12px;color:#aeb6c2}input,textarea,select{width:100%;background:#0f1216;color:#fff;border:1px solid #343a45;border-radius:9px;padding:10px}textarea{min-height:74px;resize:vertical}.equipment{grid-column:1/-1;display:grid;grid-template-columns:repeat(2,1fr);gap:10px;border-top:1px solid #282e36;padding-top:12px}.stack{display:grid;gap:7px}.preview{display:flex;gap:14px;align-items:center;padding:12px;background:#0f1216;border-radius:12px}.preview img{width:150px;height:150px;object-fit:contain;background:#171a1f;border-radius:10px}.status{margin:12px 0;padding:10px;border-radius:10px;background:#101820;color:#9ed0ff;display:none}.hidden{display:none}@media(max-width:980px){.grid{grid-template-columns:1fr}.form{grid-template-columns:1fr}.equipment{grid-template-columns:1fr}.field.full{grid-column:auto}}</style>
</head>
<body><main class="shell">
<div class="top"><div><h1>Albion Composition Admin</h1><div class="muted">Builds, composiciones, imágenes y publicación en Discord.</div></div><div class="toolbar"><input id="token" type="password" placeholder="ADMIN_TOKEN" style="min-width:260px"><button class="btn" id="saveToken">Guardar token</button></div></div>
<div class="tabs toolbar" style="margin-bottom:18px"><button data-tab="builds">Builds</button><button data-tab="compositions">Composiciones</button></div>
<div id="status" class="status"></div>
<section id="buildsTab" class="grid">
<div class="card"><div class="toolbar" style="justify-content:space-between;margin-bottom:12px"><h2 style="margin:0">Builds</h2><button class="btn primary" id="newBuild">+ Nueva build</button></div><div id="buildList" class="list"></div></div>
<div class="card"><h2 id="buildFormTitle">Nueva build</h2><form id="buildForm" class="form">
<input id="buildId" type="hidden">
<div class="field"><label>Número</label><input id="number" type="number" min="1" required></div><div class="field"><label>Estado</label><select id="buildStatus"><option value="draft">Borrador</option><option value="ready">Lista</option><option value="published">Publicada</option><option value="archived">Archivada</option></select></div>
<div class="field full"><label>Nombre</label><input id="name" required></div><div class="field"><label>Categoría</label><input id="category" required></div><div class="field"><label>Rol Discord</label><input id="roleName" required></div><div class="field"><label>ID rol Discord</label><input id="roleId" pattern="[0-9]{17,20}"></div><div class="field"><label>Canal para publicar</label><input id="publishChannel" pattern="[0-9]{17,20}" placeholder="Opcional"></div>
<div class="equipment">
<div class="field stack"><label>Arma</label><input id="weaponName" required><input id="weaponId" placeholder="Item ID opcional (override exacto)"></div>
<div class="field stack"><label>Offhand</label><input id="offhandName"><input id="offhandId" placeholder="Item ID opcional"></div>
<div class="field stack"><label>Cabeza</label><input id="headName" required><input id="headId" placeholder="Item ID opcional"></div>
<div class="field stack"><label>Pecho</label><input id="chestName" required><input id="chestId" placeholder="Item ID opcional"></div>
<div class="field stack"><label>Pies</label><input id="shoesName" required><input id="shoesId" placeholder="Item ID opcional"></div>
<div class="field stack"><label>Capa</label><input id="capeName" required><input id="capeId" placeholder="Item ID opcional"></div>
<div class="field stack"><label>Poción</label><input id="potionName" required><input id="potionId" placeholder="Item ID opcional"></div>
<div class="field stack"><label>Comida</label><input id="foodName" required><input id="foodId" placeholder="Item ID opcional"></div>
</div>
<div class="field"><label>Q</label><input id="q" required></div><div class="field"><label>W</label><input id="w" required></div><div class="field"><label>E</label><input id="e" required></div><div class="field"><label>Pasiva arma</label><input id="weaponPassive" required></div>
<div class="field"><label>Habilidad cabeza</label><input id="headAbility"></div><div class="field"><label>Pasiva cabeza</label><input id="headPassive"></div><div class="field"><label>Habilidad pecho</label><input id="chestAbility"></div><div class="field"><label>Pasiva pecho</label><input id="chestPassive"></div><div class="field"><label>Habilidad pies</label><input id="shoesAbility"></div><div class="field"><label>Pasiva pies</label><input id="shoesPassive"></div>
<div class="field full"><label>Alternativas</label><textarea id="alternatives"></textarea></div><div class="field full"><label>URL fuente</label><input id="sourceUrl" type="url"></div>
<div class="field full preview"><img id="buildImage" alt="Vista previa"><div><strong>PNG generado automáticamente</strong><p class="muted">Si dejas un Item ID vacío se usa el nombre del objeto. Usa el ID cuando necesites tier/encantamiento exactos.</p><button type="button" class="btn" id="generateImage">Generar imagen</button></div></div>
<div class="field full toolbar"><button class="btn primary" type="submit">Guardar</button><button class="btn" type="button" id="publishBuild">Publicar en Discord</button><button class="btn danger" type="button" id="archiveBuild">Archivar</button></div>
</form></div></section>
<section id="compositionsTab" class="grid hidden"><div class="card"><div class="toolbar" style="justify-content:space-between"><h2>Composiciones</h2><button class="btn primary" id="newComposition">+ Nueva</button></div><div id="compositionList" class="list"></div></div><div class="card"><h2>Editor de composición</h2><form id="compositionForm" class="form"><input id="compositionId" type="hidden"><div class="field full"><label>Nombre</label><input id="compositionName" required></div><div class="field"><label>Slug</label><input id="compositionSlug" required></div><div class="field"><label>Categoría</label><input id="compositionCategory" value="General"></div><div class="field"><label>Estado</label><select id="compositionStatus"><option value="draft">Borrador</option><option value="ready">Lista</option><option value="published">Publicada</option></select></div><div class="field"><label>Canal Discord</label><input id="compositionChannel" pattern="[0-9]{17,20}"></div><div class="field full"><label>Descripción</label><textarea id="compositionDescription"></textarea></div><div class="field full"><label>Puestos (JSON)</label><textarea id="compositionSlots" placeholder='[{"position":1,"buildId":"uuid","requiredCount":1}]'></textarea></div><div class="field full toolbar"><button class="btn primary" type="submit">Guardar composición</button><button class="btn" type="button" id="publishComposition">Publicar en Discord</button></div></form></div></section>
</main>
<script>
const $=id=>document.getElementById(id);
const val=id=>$(id).value.trim();
const nullable=id=>val(id)||null;
const notify=(message,isError=false)=>{const box=$('status');box.style.display='block';box.style.background=isError?'#301717':'#101820';box.textContent=message};
const api=async(path,options={})=>{const token=sessionStorage.getItem('adminToken')||$('token').value;const headers={...(options.headers||{}),authorization:'Bearer '+token};if(options.body)headers['content-type']='application/json';const response=await fetch(path,{...options,headers});if(!response.ok){let message='HTTP '+response.status;try{const body=await response.json();message=body.error||message}catch{}throw new Error(message)}return response.status===204?null:response.json()};
function listRow(title,subtitle,onClick){const row=document.createElement('div');row.className='row';const heading=document.createElement('div');heading.className='row-title';heading.textContent=title;const detail=document.createElement('div');detail.className='muted';detail.textContent=subtitle;row.append(heading,detail);row.onclick=onClick;return row}
$('token').value=sessionStorage.getItem('adminToken')||'';
$('saveToken').onclick=()=>{sessionStorage.setItem('adminToken',$('token').value);void loadAll()};
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{const showBuilds=button.dataset.tab==='builds';$('buildsTab').classList.toggle('hidden',!showBuilds);$('compositionsTab').classList.toggle('hidden',showBuilds)});
let builds=[];let compositions=[];
function blankBuild(){$('buildForm').reset();$('buildId').value='';$('buildStatus').value='draft';$('buildImage').removeAttribute('src');$('buildFormTitle').textContent='Nueva build'}
$('newBuild').onclick=blankBuild;
function buildPayload(){return{number:Number(val('number')),name:val('name'),category:val('category'),status:val('buildStatus'),enabled:val('buildStatus')!=='archived',discordRole:{id:val('roleId'),name:val('roleName')},equipment:{weapon:{name:val('weaponName'),q:val('q'),w:val('w'),e:val('e'),passive:val('weaponPassive')},offhand:nullable('offhandName'),head:{name:val('headName'),ability:nullable('headAbility'),passive:nullable('headPassive')},chest:{name:val('chestName'),ability:nullable('chestAbility'),passive:nullable('chestPassive')},shoes:{name:val('shoesName'),ability:nullable('shoesAbility'),passive:nullable('shoesPassive')},cape:val('capeName')},consumables:{potion:val('potionName'),food:val('foodName')},itemIds:{weapon:nullable('weaponId'),offhand:nullable('offhandId'),head:nullable('headId'),chest:nullable('chestId'),shoes:nullable('shoesId'),cape:nullable('capeId'),potion:nullable('potionId'),food:nullable('foodId')},alternatives:nullable('alternatives'),sourceUrl:nullable('sourceUrl'),imageUrl:null}}
function setValue(id,value){$(id).value=value??''}
function editBuild(build){setValue('buildId',build.id);$('buildFormTitle').textContent='#'+build.number+' · '+build.name;const values={number:build.number,name:build.name,category:build.category,buildStatus:build.status,roleName:build.discordRole.name,roleId:build.discordRole.id,weaponName:build.equipment.weapon.name,offhandName:build.equipment.offhand,headName:build.equipment.head.name,chestName:build.equipment.chest.name,shoesName:build.equipment.shoes.name,capeName:build.equipment.cape,potionName:build.consumables.potion,foodName:build.consumables.food,q:build.equipment.weapon.q,w:build.equipment.weapon.w,e:build.equipment.weapon.e,weaponPassive:build.equipment.weapon.passive,headAbility:build.equipment.head.ability,headPassive:build.equipment.head.passive,chestAbility:build.equipment.chest.ability,chestPassive:build.equipment.chest.passive,shoesAbility:build.equipment.shoes.ability,shoesPassive:build.equipment.shoes.passive,alternatives:build.alternatives,sourceUrl:build.sourceUrl,weaponId:build.itemIds?.weapon,offhandId:build.itemIds?.offhand,headId:build.itemIds?.head,chestId:build.itemIds?.chest,shoesId:build.itemIds?.shoes,capeId:build.itemIds?.cape,potionId:build.itemIds?.potion,foodId:build.itemIds?.food};Object.entries(values).forEach(([id,value])=>setValue(id,value));if(build.imageUrl)$('buildImage').src=build.imageUrl;else $('buildImage').removeAttribute('src')}
async function loadBuilds(){builds=await api('/api/admin/builds');const list=$('buildList');list.replaceChildren();for(const build of builds)list.appendChild(listRow('#'+build.number+' · '+build.discordRole.name,build.category+' · '+build.status,()=>editBuild(build)))}
$('buildForm').onsubmit=async event=>{event.preventDefault();try{const id=val('buildId');const saved=id?await api('/api/admin/builds/'+id,{method:'PUT',body:JSON.stringify(buildPayload())}):await api('/api/admin/builds',{method:'POST',body:JSON.stringify(buildPayload())});await loadBuilds();editBuild(saved);notify('Build guardada.')}catch(error){notify(error instanceof Error?error.message:String(error),true)}};
$('generateImage').onclick=async()=>{try{const id=val('buildId');if(!id)throw new Error('Guarda la build antes de generar la imagen.');const build=await api('/api/admin/builds/'+id+'/generate-image',{method:'POST'});await loadBuilds();editBuild(build);notify('PNG generado y almacenado.')}catch(error){notify(error instanceof Error?error.message:String(error),true)}};
$('publishBuild').onclick=async()=>{try{const id=val('buildId');if(!id)throw new Error('Guarda la build primero.');await api('/api/admin/builds/'+id+'/publish',{method:'POST',body:JSON.stringify({channelId:nullable('publishChannel')})});notify('Build publicada en Discord.')}catch(error){notify(error instanceof Error?error.message:String(error),true)}};
$('archiveBuild').onclick=async()=>{try{const id=val('buildId');if(!id)return;await api('/api/admin/builds/'+id,{method:'DELETE'});blankBuild();await loadBuilds();notify('Build archivada.')}catch(error){notify(error instanceof Error?error.message:String(error),true)}};
function blankComposition(){$('compositionForm').reset();$('compositionId').value='';$('compositionCategory').value='General';$('compositionStatus').value='draft'}
$('newComposition').onclick=blankComposition;
function editComposition(composition){setValue('compositionId',composition.id);setValue('compositionName',composition.name);setValue('compositionSlug',composition.slug);setValue('compositionCategory',composition.category);setValue('compositionStatus',composition.status);setValue('compositionChannel',composition.discordChannelId);setValue('compositionDescription',composition.description);setValue('compositionSlots',JSON.stringify(composition.slots.map(slot=>({position:slot.position,buildId:slot.buildId,label:slot.label,requiredCount:slot.requiredCount})),null,2))}
async function loadCompositions(){compositions=await api('/api/admin/compositions');const list=$('compositionList');list.replaceChildren();for(const composition of compositions)list.appendChild(listRow(composition.name,composition.category+' · '+composition.slots.length+' puestos · '+composition.status,()=>editComposition(composition)))}
function compositionPayload(){return{name:val('compositionName'),slug:val('compositionSlug'),category:val('compositionCategory'),status:val('compositionStatus'),discordChannelId:nullable('compositionChannel'),description:nullable('compositionDescription'),slots:val('compositionSlots')?JSON.parse(val('compositionSlots')):[]}}
$('compositionForm').onsubmit=async event=>{event.preventDefault();try{const id=val('compositionId');const saved=id?await api('/api/admin/compositions/'+id,{method:'PUT',body:JSON.stringify(compositionPayload())}):await api('/api/admin/compositions',{method:'POST',body:JSON.stringify(compositionPayload())});await loadCompositions();editComposition(saved);notify('Composición guardada.')}catch(error){notify(error instanceof Error?error.message:String(error),true)}};
$('publishComposition').onclick=async()=>{try{const id=val('compositionId');if(!id)throw new Error('Guarda la composición primero.');await api('/api/admin/compositions/'+id+'/publish',{method:'POST',body:JSON.stringify({channelId:nullable('compositionChannel')})});notify('Composición publicada en Discord.')}catch(error){notify(error instanceof Error?error.message:String(error),true)}};
async function loadAll(){try{await Promise.all([loadBuilds(),loadCompositions()]);notify('Datos sincronizados con PostgreSQL.')}catch(error){notify('No se pudo cargar el panel: '+(error instanceof Error?error.message:String(error)),true)}}
if($('token').value)void loadAll();
</script></body></html>`;
}
